name: CI

on:
  push:
    branches: 
      - develop

jobs:
  build:
    name: "[DEV] Build and deploy to github pages"
    runs-on: [ubuntu-latest]
    steps:
      - name: pwd
        run: pwd
#     - name: GitHub Pages Deploy
#     - uses: maxheld83/ghpages@v0.2.1
      
