name: Build and deploy to github pages

on:
  push:
    branches: 
      - develop

jobs:
  build:
    name: "[DEV] Build and deploy to github pages"
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        working-directory: web-app
      - name: Build web-app
        run: yarn build
        working-directory: web-app
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
        env: 
          BUILD_DIR: "web-app/public/"
